### ISSUE TITLE
Question: Does pod-reaper need ClusterRole binding ?

### ISSUE THREAD

**Issue by RaymondKYLiu** [target/pod-reaper#41]
Hi, thanks for your tool.
I'd like to apply pod-reaper to my k8s cluster, but In the example `deployment.yaml`, I don't see any policy setting for granting pod-reaper to have permission to delete pods.

**Comment by brianberzins** [comment]
Thanks for the feedback!

The permissions come from the service account running the pod. Looking back, I completely understand how this is not obvious!

I'll try to get some documentation up on this over the weekend and provide examples with minimal permissions!

**Comment by brianberzins** [comment]
At the risk of going completely overboard with this answer:

Pod reaper needs be running with a service account that has permissions to both list and delete pods.

By default, pod-reaper tries to list pods from the entire cluster. To accomplish this, the service account will need to be bound to a `ClusterRole` with list and delete permissions via a `ClusterRoleBinding`. 

If instead of operating against the entire cluster, you want pod reaper to only operate against a specific namespace, then that can be accomplished with a `Role` and `RoleBinding`

So I want to break down three cases:
1. Running against a cluster
1. Running from a namespace, against that same namespace
1. Running from one namespace, against a different namespace

I just poked around with case number 2 on a version v1.17.0 cluster. The entirety of example is pasted below the explanation!

- a namespace called `test`
- a service account `pod-reaper-service-account` in the `test` namespace
- a role `pod-reaper-role` in the `test` namespace with pod-reapers minimal permissions
- a role-binding `pod-reaper-role-binding` in the `test` namespace to add the permissions of the above role to the above service account.
- a deployment of pod-reaper. There are two important points here
  - the environment variable `NAMESPACE` is set to `test` (the namespace from above) -- this tells the reaper to only look for pods in that namespace instead of cluster wide
  - the pod spec indicates that it should be run with the `pod-reaper-service-account` from above
- a deployment of pods that just `sleep infinity` so you can see the reaper in action

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reaper-service-account
  namespace: test

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: test
  name: pod-reaper-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pod-reaper-role-binding
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reaper-role
subjects:
- kind: ServiceAccount
  name: pod-reaper-service-account
  namespace: test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-reaper
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-reaper
  template:
    metadata:
      labels:
        app: pod-reaper
        pod-reaper: disabled
    spec:
      serviceAccount: pod-reaper-service-account
      containers:
      - name: unready
        image: target/pod-reaper
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi
        env:
          - name: NAMESPACE
            value: test
          - name: SCHEDULE
            value: "@every 15s"
          - name: EXCLUDE_LABEL_KEY
            value: pod-reaper
          - name: EXCLUDE_LABEL_VALUES
            value: disabled
          - name: CHAOS_CHANCE
            value: ".05"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper
  namespace: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      containers:
      - name: sleeper
        image: ubuntu
        command:
          - /bin/sh
          - -c
          - sleep infinity
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi    
```

More to come with the other two cases!

**Comment by brianberzins** [comment]
case 1 from above:

Running at the cluster level. In this case a `ClusterRoleBinding` and `ClusterRole` are required. Here's the full example I used to demonstrate this!

Note the differences from above:
- cluster role binding (instead of role binding)
- cluster role (instead of role)
- not specifying the namespace (although these permissions can be used for running namespace specific reapers)

```
# namespace for testing
---
apiVersion: v1
kind: Namespace
metadata:
  name: test

# different namespace for the reaper
---
apiVersion: v1
kind: Namespace
metadata:
  name: reaper

# service account for running pod-reaper
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reaper-service-account
  namespace: reaper

# minimal permissions required for running pod-reaper at cluster level
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-reaper-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]

# binding the above cluster role (permissions) to the above service account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pod-reaper-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reaper-cluster-role
subjects:
- kind: ServiceAccount
  name: pod-reaper-service-account
  namespace: reaper

# pod-reaper deployment
#   runing with the above service account 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-reaper
  namespace: reaper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-reaper
  template:
    metadata:
      labels:
        app: pod-reaper
        pod-reaper: disabled
    spec:
      serviceAccount: pod-reaper-service-account
      containers:
      - name: chaos
        image: target/pod-reaper
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi
        env:
          - name: SCHEDULE
            value: "@every 15s"
          - name: EXCLUDE_LABEL_KEY
            value: pod-reaper
          - name: EXCLUDE_LABEL_VALUES
            value: disabled
          - name: CHAOS_CHANCE
            value: ".05"

# deployment of 'sleeping' pods to demonstrate reaping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleeper
  namespace: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      containers:
      - name: sleeper
        image: ubuntu
        command:
          - /bin/sh
          - -c
          - sleep infinity
        resources:
          limits:
            cpu: 30m
            memory: 30Mi
          requests:
            cpu: 20m
            memory: 20Mi    
```

Some logs to demonstrate that it's operating at the cluster level:

```
{"level":"info","msg":"reaping pod","pod":"sleeper-769fc94b99-bmsf7","reasons":["was flagged for chaos"],"time":"2020-02-08T13:25:35Z"}
{"level":"info","msg":"reaping pod","pod":"sleeper-769fc94b99-shqkh","reasons":["was flagged for chaos"],"time":"2020-02-08T13:26:05Z"}
{"level":"info","msg":"reaping pod","pod":"kube-proxy-f66ws","reasons":["was flagged for chaos"],"time":"2020-02-08T13:26:50Z"}
{"level":"info","msg":"reaping pod","pod":"kube-scheduler-kind-control-plane","reasons":["was flagged for chaos"],"time":"2020-02-08T13:26:50Z"}
{"level":"info","msg":"reaping pod","pod":"kube-apiserver-kind-control-plane","reasons":["was flagged for chaos"],"time":"2020-02-08T13:27:05Z"}
{"level":"info","msg":"reaping pod","pod":"kube-controller-manager-kind-control-plane","reasons":["was flagged for chaos"],"time":"2020-02-08T13:27:20Z"}
{"level":"info","msg":"reaping pod","pod":"kube-proxy-ld2sw","reasons":["was flagged for chaos"],"time":"2020-02-08T13:27:20Z"}
{"level":"info","msg":"reaping pod","pod":"sleeper-769fc94b99-7mf4m","reasons":["was flagged for chaos"],"time":"2020-02-08T13:27:20Z"}
```
